#!/usr/bin/python3

# Delwink Software
# coinfetch
#
# This script is free software, released under the terms of the MIT license.
# See LICENSE for more information.
#
# This release of coinfetch is maintained by Delwink Software.
#
# Feature requests: sales@delwink.com
# Links to PGP keys available at http://delwink.com/contact.html
#
# Donate to Delwink!
# BTC  - 1HLpZxHSMbaq2pCeYRtYMsSYMFtsuSDknX
# LTC  - LYzCqLD5nrf1hnRe5uKpeThDDXd3B3TawC
# DOGE - DSiVFYZmMCykf5ALqBNwiah8h1zKqT4sZo

##### ORIGINAL DEVELOPER COMMENTS #####

# Wow such python
# Feel free to modify
# So generous: DGSWzqyofHC6YDSA34hwVQpWGQHnzJm1sk
#
# Values retrieved are in the form 
#		1 <coin_a> = <printed output> <coin_b>
#
# Remember to make this file executable ( "$chmod +x ./coinfetch" )

##### END ORIGINAL DEVELOPER COMMENTS #####

import requests, sys

def coinfetch(coin_a, coin_b):
	"""
	Fetch a coin pair
	"""
	url = 'http://data.bter.com/api/1/tickers'
	r = requests.get(url)
	try:
		pair = coin_a+"_"+coin_b
		out = float(r.json()[pair]['avg'])
	except:
		pair = coin_b+"_"+coin_a
		out = float((r.json()[pair]['avg']))**-1
	return out

try:
# To change precision of output, replace the 8 with the desired number of decimal places.
	print ("%.8f" %coinfetch(sys.argv[1], sys.argv[2]))	
except KeyError:
	exit("Coinpair not found.")
except IndexError:
	exit("Enter an argument!!")
